version: '2'
services:
  api:
    build: .
    stdin_open: true
    command: bash -c "pip3 install -r /daas/pip_requirements.txt && python3 /daas/daas/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/daas
      - /tmp/:/tmp/
      - ./utils/just_decompile:/just_decompile/
    ports:
      - "8000:8000"
    links:
      - syslog
    tmpfs:
      - /tmpfs
    logging:
      driver: syslog
      options:
        syslog-address: "udp://127.0.0.1:5514"
        tag: "worker"

  redis:
    image: redis:4.0.10
    ports:
      - "6379:6379"
    links:
      - api
      - syslog
    logging:
      driver: syslog
      options:
        syslog-address: "udp://127.0.0.1:5514"
        tag: "redis"

  mongo_db:
    image: mongo:4.1.2
    volumes:
      - ../mongo-data/:/data/db
    links:
      - syslog
    logging:
      driver: syslog
      options:
        syslog-address: "udp://127.0.0.1:5514"
        tag: "mongo_db"

  syslog:
    image: voxxit/rsyslog
    volumes:
      - ../syslog/:/var/log/
    entrypoint: bash -c "rm -f /var/run/rsyslogd.pid && rsyslogd -n"
    ports:
        - "127.0.0.1:5514:514/udp"
