version: '3.7'
services:
  api:
    build:
      context: .
      target: testing
    command: bash -c "python3 /daas/manage.py collectstatic --no-input && cd /daas/ && gunicorn daas.wsgi --timeout 300 -b 0.0.0.0:8001"
    volumes:
      - ./daas:/daas
      - /daas/daas_app/tests/resources/ # to not mount tests resources
      - ./static:/static
      - ./gunicorn_config/:/home/root/conf
    expose:
      - "8001"
      - "4567-4667"
    depends_on:
      - db
    links:
      - syslog
    tmpfs:
      - /tmpfs
    logging:
      driver: syslog
      options:
        syslog-address: "udp://127.0.0.1:5514"
        tag: "api"

  redis_task_queue:
    image: redis:5.0.6
    expose:
      - "6379"
    depends_on:
      - api
    links:
      - syslog
    logging:
      driver: syslog
      options:
        syslog-address: "udp://127.0.0.1:5514"
        tag: "redis_task_queue"

  redis_statistics:
    image: redis:5.0.6
    command: "redis-server --port 6380 --appendonly yes"
    volumes:
      - ../statistics-data:/data
    expose:
      - "6380"
    depends_on:
      - api
    links:
      - syslog
    logging:
      driver: syslog
      options:
        syslog-address: "udp://127.0.0.1:5514"
        tag: "redis_statistics"

  db:
    image: postgres:10.5
    expose:
      - "5432"
    volumes:
      - ../postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: daas
      POSTGRES_PASSWORD: iamaweakpassword
      POSTGRES_DB: daas
    links:
      - syslog
    logging:
      driver: syslog
      options:
        syslog-address: "udp://127.0.0.1:5514"
        tag: "db"

  pe_worker:
    build:
      context: .
      dockerfile: peWorkerDockerfile
    command: bash -c "rq worker --path / --url redis://daas_redis_task_queue_1:6379/0 pe_queue --name agent_$$(hostname -I | cut -d' ' -f1)_$$(echo $$RANDOM)__$$(date +%s)"
    volumes:
      - ./decompilers:/daas
      - ./utils/just_decompile:/just_decompile/
    tmpfs:
      - /tmpfs
    links:
      - redis_task_queue
      - syslog
    logging:
      driver: syslog
      options:
        syslog-address: "udp://127.0.0.1:5514"
        tag: "pe_worker"

  flash_worker:
    build:
      context: .
      dockerfile: flashWorkerDockerfile
    command: bash -c "rq worker --path / --url redis://daas_redis_task_queue_1:6379/0 flash_queue --name agent_$$(hostname -I | cut -d' ' -f1)_$$(echo $$RANDOM)__$$(date +%s)"
    volumes:
      - ./decompilers:/daas
    tmpfs:
      - /tmpfs
    links:
      - redis_task_queue
      - syslog
    logging:
      driver: syslog
      options:
        syslog-address: "udp://127.0.0.1:5514"
        tag: "flash_worker"

  java_worker:
    build:
      context: .
      dockerfile: javaWorkerDockerfile
    command: bash -c "rq worker --path / --url redis://daas_redis_task_queue_1:6379/0 java_queue --name agent_$$(hostname -I | cut -d' ' -f1)_$$(echo $$RANDOM)__$$(date +%s)"
    volumes:
      - ./decompilers:/daas
    tmpfs:
      - /tmpfs
    links:
      - redis_task_queue
      - syslog
    logging:
      driver: syslog
      options:
        syslog-address: "udp://127.0.0.1:5514"
        tag: "java_worker"

  syslog:
    image: voxxit/rsyslog
    # container_name: daas_syslog_1
    volumes:
      - ../syslog/:/var/log/
    entrypoint: bash -c "rm -f /var/run/rsyslogd.pid && rsyslogd -n"
    ports:
        - "127.0.0.1:5514:514/udp"

  nginx:
    image: nginx:1.15.8
    volumes:
      - ./nginx_config:/etc/nginx/conf.d
      - ./certificates/etc_ssl_certs:/etc/ssl/certs
      - ./certificates/etc_ssl_private:/etc/ssl/private
      - ./nginx_snippets:/etc/nginx/snippets
      - ./daas/static:/static_files
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
    logging:
      driver: syslog
      options:
        syslog-address: "udp://127.0.0.1:5514"
        tag: "nginx"
