version: 2
jobs:
  build:
    resource_class: large
    machine:
      enabled: true
    working_directory: ~/daas
    steps:
      - checkout
      - run: free -h
      - run: pip install --retries 10 --timeout 30 docker-compose==1.20.1 docker==3.1.4
      - run: docker-compose up -d syslog
      - run: docker-compose up -d db
      - run:
          command: docker-compose up -d api
          no_output_timeout: 20m
      - run: sleep 10 && free -h && docker-compose ps
      - run:
          name: check containers. If at least one is down, print logs
          command: |
            if [ $(docker-compose  ps | grep exit | wc -l) -ne "0" ]; then
               docker-compose exec syslog cat /var/log/messages
            fi
      - run: docker-compose exec syslog cat /var/log/messages
      - run: docker-compose exec api sh -c "pip freeze"
      - run: docker-compose exec api sh -c "apt list"
      - run: docker-compose exec api sh -c "python /daas/daas/manage.py makemigrations daas_app"
      - run: docker-compose exec api sh -c "python /daas/daas/manage.py migrate"
      - run:
          name: executing tests
          command: docker-compose exec api sh -c "coverage run --source='/daas/daas/daas_app' /daas/daas/manage.py test daas_app.tests -v 1 --force-color --exclude stress_test_csharp --noinput "
      - run:
          name: executing tests in reverse order
          command: docker-compose exec api sh -c "python /daas/daas/manage.py test daas_app.tests --reverse -v 1 --force-color --exclude stress_test_csharp --noinput "
      - run: docker-compose up -d redis_task_queue
      - run:
          name: executing stress tests
          no_output_timeout: 60m
          command: docker-compose exec api sh -c "python /daas/daas/manage.py test daas_app.tests.stress_test_csharp -v 1 --force-color --noinput "
      - run:
          name: print logs on fail
          command: docker-compose exec syslog cat /var/log/messages
          when: on_fail
      - run:
          name: check containers
          command: docker-compose ps
      - run:
          name: executing coverage
          command: docker-compose exec api sh -c "coverage report -m --fail-under=70 --omit='*daas_app/tests/*,*daas_app/migrations/*,*daas_app/decompilers*'"
